library(lubridate)

library(sf)
library(tigris)

library(magrittr)
library(tidyverse)
library(feather)

import::from(segmented, .except = "select")
library(fixest)
library(robslopes)
library(strucchange)

library(gtable)
library(cowplot)
library(geofacet)
library(ggforce)
library(ggridges)
library(MetBrewer)
library(usmap)
library(scales)

library(foreach)
library(parallel)
library(doParallel)
library(future.apply)
library(future.callr)
library(doRNG)
library(doFuture)
library(tictoc)
library(callr)
